add dwarf parser
fix uninstall

remove sdb check

diff --git a/db/libdwarf b/db/libdwarf
--- a/db/libdwarf
+++ b/db/libdwarf
@@ -4,6 +4,9 @@ R2PM_GIT "git://git.code.sf.net/p/libdwarf/code" libdwarf-code
 R2PM_DESC "libdwarf - git"
 
 R2PM_INSTALL() {
+	if ! $(pkg-config --exists libelf) || ! $(pkg-config --exists zlib); then
+		echo "ERROR: Libraries required: libelf and zlib"; exit 1
+	fi
 	./configure --prefix="${R2PM_PREFIX}"
 	${MAKE}
 }
