Update r2ghidra

diff --git a/db/r2ghidra b/db/r2ghidra
--- a/db/r2ghidra
+++ b/db/r2ghidra
@@ -19,8 +19,8 @@ R2PM_INSTALL() {
 	rm -rf ghidra/ghidra/Ghidra
 	rm -rf build # clean build
 	./preconfigure || exit 1
-	./configure --prefix=`r2 -H R2_PREFIX` || R2PM_FAIL "configure"
-	${MAKE} -C src -j1 || R2PM_FAIL "make"
+	./configure --prefix=`r2 -H R2_PREFIX` || { echo "Error: 'configure' failed for r2ghidra"; exit 1; }
+	${MAKE} -C src -j1 || { echo "Error: 'make' failed for r2ghidra"; exit 1; }
 	if [ "${GLOBAL}" = 1 ]; then
 		${SUDO} ${MAKE} -C src install
 	else
