Update r2yara

diff --git a/db/r2yara b/db/r2yara
--- a/db/r2yara
+++ b/db/r2yara
@@ -5,12 +5,12 @@ R2PM_DESC "yara plugin for radare2"
 R2PM_DEPS yara
 
 R2PM_INSTALL() {
-	./configure --prefix="${R2PM_PREFIX}" || R2PM_FAIL "Configure"
-	${MAKE} || R2PM_FAIL "Build"
+	./configure --prefix="${R2PM_PREFIX}" || { echo "Error: 'Configure' failed."; exit 1; }
+	${MAKE} || { echo "Error: 'Build' failed."; exit 1; }
 	if [ "${R2PM_GLOBAL}" = 1 ]; then
-		${SUDO} ${MAKE} install || R2PM_FAIL "Install"
+		${SUDO} ${MAKE} install || { echo "Error: 'Install' failed."; exit 1; }
 	else
-		${MAKE} user-install || R2PM_FAIL "Install"
+		${MAKE} user-install || { echo "Error: 'Install' failed."; exit 1; }
 	fi
 }
 
