Update yara-r2

diff --git a/db/yara-r2 b/db/yara-r2
--- a/db/yara-r2
+++ b/db/yara-r2
@@ -9,18 +9,18 @@ R2PM_INSTALL() {
 
 if [ 1 = 0 ]; then
 	# libjansson
-	wget -c http://www.digip.org/jansson/releases/jansson-2.7.tar.gz || R2PM_FAIL "Downloading libjansson"
-	tar -xzvf jansson-2.7.tar.gz || R2PM_FAIL "Unpacking libjansson"
-	cd jansson-2.7 || R2PM_FAIL "Entering libjansson folder"
-	./configure --prefix="${R2PM_PREFIX}" || R2PM_FAIL "Configuring libjansson"
-	${MAKE} || R2PM_FAIL "Building libjansson"
-	${R2PM_SUDO} ${MAKE} install || R2PM_FAIL "Installing libjansson"
+	wget -c http://www.digip.org/jansson/releases/jansson-2.7.tar.gz || { echo "Error: Downloading libjansson failed"; exit 1; }
+	tar -xzvf jansson-2.7.tar.gz || { echo "Error: Unpacking libjansson failed"; exit 1; }
+	cd jansson-2.7 || { echo "Error: Entering libjansson folder failed"; exit 1; }
+	./configure --prefix="${R2PM_PREFIX}" || { echo "Error: Configuring libjansson failed"; exit 1; }
+	${MAKE} || { echo "Error: Building libjansson failed"; exit 1; }
+	${R2PM_SUDO} ${MAKE} install || { echo "Error: Installing libjansson failed"; exit 1; }
 	cd ..
 	fi
 if [ 1 = 1 ] ; then
 	if [ ! -d yara ]; then
 	# Yara
-	git clone https://github.com/VirusTotal/yara || R2PM_FAIL "Cloning Yara"
+	git clone https://github.com/VirusTotal/yara || { echo "Error: Cloning Yara failed"; exit 1; }
 	# pin the commit
 	fi
 	( cd yara && git reset --hard)
@@ -39,10 +39,10 @@ fi
 	export CFLAGS="-I${R2PM_PREFIX}/include"
 	export LDFLAGS="-L${R2PM_PREFIX}/lib"
 	cd yara || exit 1
-	./bootstrap.sh || R2PM_FAIL "Bootstrap Yara"
-	./configure --prefix="${R2PM_PREFIX}" --enable-cuckoo || R2PM_FAIL "Configure has failed"
-	${MAKE} || R2PM_FAIL "Build"
-	${R2PM_SUDO} ${MAKE} install || R2PM_FAIL "Install"
+	./bootstrap.sh || { echo "Error: Bootstrap Yara failed"; exit 1; }
+	./configure --prefix="${R2PM_PREFIX}" --enable-cuckoo || { echo "Error: Configure has failed"; exit 1; }
+	${MAKE} || { echo "Error: Build failed"; exit 1; }
+	${R2PM_SUDO} ${MAKE} install || { echo "Error: Install failed"; exit 1; }
 }
 
 R2PM_UNINSTALL() {
